// Generated by scripts/gen-abi.mjs — do not edit by hand.
export const CONTRACT_ABI = [
{
  "type": "constructor",
  "inputs": [],
  "stateMutability": "nonpayable"
},
{
  "type": "function",
  "name": "KIND_OPTIONS",
  "inputs": [],
  "outputs": [
    {
      "name": "",
      "type": "uint8",
      "internalType": "uint8"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "KIND_RATING",
  "inputs": [],
  "outputs": [
    {
      "name": "",
      "type": "uint8",
      "internalType": "uint8"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "KIND_TEXT",
  "inputs": [],
  "outputs": [
    {
      "name": "",
      "type": "uint8",
      "internalType": "uint8"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "KIND_YESNO",
  "inputs": [],
  "outputs": [
    {
      "name": "",
      "type": "uint8",
      "internalType": "uint8"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "MAX_FRAMES",
  "inputs": [],
  "outputs": [
    {
      "name": "",
      "type": "uint256",
      "internalType": "uint256"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "XP_PER_CORRECT",
  "inputs": [],
  "outputs": [
    {
      "name": "",
      "type": "uint256",
      "internalType": "uint256"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "accumulatedFees",
  "inputs": [],
  "outputs": [
    {
      "name": "",
      "type": "uint256",
      "internalType": "uint256"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "closeTask",
  "inputs": [
    {
      "name": "taskId",
      "type": "uint256",
      "internalType": "uint256"
    }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
},
{
  "type": "function",
  "name": "createTask",
  "inputs": [
    {
      "name": "title",
      "type": "string",
      "internalType": "string"
    },
    {
      "name": "description",
      "type": "string",
      "internalType": "string"
    },
    {
      "name": "category",
      "type": "string",
      "internalType": "string"
    },
    {
      "name": "kind",
      "type": "uint8",
      "internalType": "uint8"
    },
    {
      "name": "optionCount",
      "type": "uint8",
      "internalType": "uint8"
    },
    {
      "name": "options",
      "type": "string[]",
      "internalType": "string[]"
    },
    {
      "name": "rewardPerFrame",
      "type": "uint256",
      "internalType": "uint256"
    },
    {
      "name": "frameCount",
      "type": "uint256",
      "internalType": "uint256"
    },
    {
      "name": "goldenAnswers",
      "type": "bytes32[]",
      "internalType": "bytes32[]"
    }
  ],
  "outputs": [
    {
      "name": "id",
      "type": "uint256",
      "internalType": "uint256"
    }
  ],
  "stateMutability": "payable"
},
{
  "type": "function",
  "name": "dayStreak",
  "inputs": [
    {
      "name": "",
      "type": "address",
      "internalType": "address"
    }
  ],
  "outputs": [
    {
      "name": "",
      "type": "uint32",
      "internalType": "uint32"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "getLeaderboard",
  "inputs": [
    {
      "name": "limit",
      "type": "uint256",
      "internalType": "uint256"
    }
  ],
  "outputs": [
    {
      "name": "addrs",
      "type": "address[]",
      "internalType": "address[]"
    },
    {
      "name": "pts",
      "type": "uint256[]",
      "internalType": "uint256[]"
    },
    {
      "name": "wins",
      "type": "uint32[]",
      "internalType": "uint32[]"
    },
    {
      "name": "streakDays",
      "type": "uint32[]",
      "internalType": "uint32[]"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "getTask",
  "inputs": [
    {
      "name": "taskId",
      "type": "uint256",
      "internalType": "uint256"
    }
  ],
  "outputs": [
    {
      "name": "",
      "type": "tuple",
      "internalType": "struct MicroTask.Task",
      "components": [
        {
          "name": "id",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "creator",
          "type": "address",
          "internalType": "address"
        },
        {
          "name": "title",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "description",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "category",
          "type": "string",
          "internalType": "string"
        },
        {
          "name": "kind",
          "type": "uint8",
          "internalType": "uint8"
        },
        {
          "name": "optionCount",
          "type": "uint8",
          "internalType": "uint8"
        },
        {
          "name": "options",
          "type": "string[]",
          "internalType": "string[]"
        },
        {
          "name": "reward",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "bounty",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "completed",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "rejected",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "frameCount",
          "type": "uint256",
          "internalType": "uint256"
        },
        {
          "name": "active",
          "type": "bool",
          "internalType": "bool"
        }
      ]
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "lastCorrectDay",
  "inputs": [
    {
      "name": "",
      "type": "address",
      "internalType": "address"
    }
  ],
  "outputs": [
    {
      "name": "",
      "type": "uint48",
      "internalType": "uint48"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "owner",
  "inputs": [],
  "outputs": [
    {
      "name": "",
      "type": "address",
      "internalType": "address"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "points",
  "inputs": [
    {
      "name": "",
      "type": "address",
      "internalType": "address"
    }
  ],
  "outputs": [
    {
      "name": "",
      "type": "uint256",
      "internalType": "uint256"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "protocolFee",
  "inputs": [],
  "outputs": [
    {
      "name": "",
      "type": "uint256",
      "internalType": "uint256"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "submitAnswer",
  "inputs": [
    {
      "name": "taskId",
      "type": "uint256",
      "internalType": "uint256"
    },
    {
      "name": "frameId",
      "type": "uint256",
      "internalType": "uint256"
    },
    {
      "name": "answer",
      "type": "bytes32",
      "internalType": "bytes32"
    }
  ],
  "outputs": [],
  "stateMutability": "nonpayable"
},
{
  "type": "function",
  "name": "taskCount",
  "inputs": [],
  "outputs": [
    {
      "name": "",
      "type": "uint256",
      "internalType": "uint256"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "tasks",
  "inputs": [
    {
      "name": "",
      "type": "uint256",
      "internalType": "uint256"
    }
  ],
  "outputs": [
    {
      "name": "id",
      "type": "uint256",
      "internalType": "uint256"
    },
    {
      "name": "creator",
      "type": "address",
      "internalType": "address"
    },
    {
      "name": "title",
      "type": "string",
      "internalType": "string"
    },
    {
      "name": "description",
      "type": "string",
      "internalType": "string"
    },
    {
      "name": "category",
      "type": "string",
      "internalType": "string"
    },
    {
      "name": "kind",
      "type": "uint8",
      "internalType": "uint8"
    },
    {
      "name": "optionCount",
      "type": "uint8",
      "internalType": "uint8"
    },
    {
      "name": "reward",
      "type": "uint256",
      "internalType": "uint256"
    },
    {
      "name": "bounty",
      "type": "uint256",
      "internalType": "uint256"
    },
    {
      "name": "completed",
      "type": "uint256",
      "internalType": "uint256"
    },
    {
      "name": "rejected",
      "type": "uint256",
      "internalType": "uint256"
    },
    {
      "name": "frameCount",
      "type": "uint256",
      "internalType": "uint256"
    },
    {
      "name": "active",
      "type": "bool",
      "internalType": "bool"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "winStreak",
  "inputs": [
    {
      "name": "",
      "type": "address",
      "internalType": "address"
    }
  ],
  "outputs": [
    {
      "name": "",
      "type": "uint32",
      "internalType": "uint32"
    }
  ],
  "stateMutability": "view"
},
{
  "type": "function",
  "name": "withdrawFees",
  "inputs": [],
  "outputs": [],
  "stateMutability": "nonpayable"
},
{
  "type": "event",
  "name": "AnswerAccepted",
  "inputs": [
    {
      "name": "taskId",
      "type": "uint256",
      "indexed": true,
      "internalType": "uint256"
    },
    {
      "name": "frameId",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256"
    },
    {
      "name": "worker",
      "type": "address",
      "indexed": false,
      "internalType": "address"
    },
    {
      "name": "amount",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256"
    }
  ],
  "anonymous": false
},
{
  "type": "event",
  "name": "AnswerPending",
  "inputs": [
    {
      "name": "taskId",
      "type": "uint256",
      "indexed": true,
      "internalType": "uint256"
    },
    {
      "name": "frameId",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256"
    },
    {
      "name": "worker",
      "type": "address",
      "indexed": false,
      "internalType": "address"
    },
    {
      "name": "option",
      "type": "uint8",
      "indexed": false,
      "internalType": "uint8"
    }
  ],
  "anonymous": false
},
{
  "type": "event",
  "name": "AnswerRejected",
  "inputs": [
    {
      "name": "taskId",
      "type": "uint256",
      "indexed": true,
      "internalType": "uint256"
    },
    {
      "name": "frameId",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256"
    },
    {
      "name": "worker",
      "type": "address",
      "indexed": false,
      "internalType": "address"
    },
    {
      "name": "option",
      "type": "uint8",
      "indexed": false,
      "internalType": "uint8"
    }
  ],
  "anonymous": false
},
{
  "type": "event",
  "name": "TaskClosed",
  "inputs": [
    {
      "name": "taskId",
      "type": "uint256",
      "indexed": true,
      "internalType": "uint256"
    }
  ],
  "anonymous": false
},
{
  "type": "event",
  "name": "TaskCreated",
  "inputs": [
    {
      "name": "id",
      "type": "uint256",
      "indexed": true,
      "internalType": "uint256"
    },
    {
      "name": "creator",
      "type": "address",
      "indexed": false,
      "internalType": "address"
    },
    {
      "name": "category",
      "type": "string",
      "indexed": false,
      "internalType": "string"
    },
    {
      "name": "reward",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256"
    }
  ],
  "anonymous": false
},
{
  "type": "event",
  "name": "XpEarned",
  "inputs": [
    {
      "name": "worker",
      "type": "address",
      "indexed": true,
      "internalType": "address"
    },
    {
      "name": "points",
      "type": "uint256",
      "indexed": false,
      "internalType": "uint256"
    },
    {
      "name": "winStreak",
      "type": "uint32",
      "indexed": false,
      "internalType": "uint32"
    },
    {
      "name": "dayStreak",
      "type": "uint32",
      "indexed": false,
      "internalType": "uint32"
    }
  ],
  "anonymous": false
}
] as const;

export type ContractAbi = typeof CONTRACT_ABI;
