import { readFileSync, writeFileSync } from "node:fs";

const artifact = JSON.parse(
  readFileSync(new URL("../contracts/out/MicroTask.sol/MicroTask.json", import.meta.url), "utf8"),
);

const abi = artifact.abi;

const body = abi
  .map((item) => JSON.stringify(item, null, 2))
  .join(",\n");

const out = `// Generated by scripts/gen-abi.mjs — do not edit by hand.\nexport const CONTRACT_ABI = [\n${body}\n] as const;\n\nexport type ContractAbi = typeof CONTRACT_ABI;\n`;

writeFileSync(new URL("../lib/abi.ts", import.meta.url), out);
console.log(`Wrote lib/abi.ts with ${abi.length} ABI entries.`);